language: cpp

jobs:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode11.2
      env:
        - MACOSX_DEPLOYMENT_TARGET=10.14
        - MATRIX_EVAL=""

    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - GCC_VER="10"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-10
            - g++-10
            - doxygen
      after_script:
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-${GCC_VER}
    - os: linux
      dist: bionic
      compiler: clang
      before_install:  # Overrides before_install step below
        # Add LLVM repo and GPG key so we can install clang-10
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        - echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" | sudo tee -a /etc/apt/sources.list
        - sudo apt-get -qq update
        - sudo apt-get -y install clang-10
      env:
        - CLANG_VER="10"
        - MATRIX_EVAL="CC=clang-${CLANG_VER} && CXX=clang++-${CLANG_VER}"
      addons: { apt: { packages: ['doxygen'] } }

before_install: skip
  # Empty. We are using this step to add sources (as in addons/apt/sources) 
  # that Travis disallows, for example, the LLVM repo.

install: skip

before_script:
  # Set CC and CXX
  - eval "${MATRIX_EVAL}"

  # Set default version of Python to 3: works the same way on Mac and Linux
  - pip install virtualenv
  - virtualenv -p python3 ~/venv
  - source ~/venv/bin/activate

  # Fail if we are using the wrong Python
  - python --version | grep -iE 'python\s*3'
  - pip    --version | grep -iE 'python\s*3'
  
  # Install Conan using Python 3.
  - pip install conan cmake
  
  # Fail if we can't run Conan.
  - conan --version

script:
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE .
  - cmake --build . -- -j2
  - ctest -j2
